local M = {}

M.newtestament = {
	"Matthew",
	"Mark",
	"Luke",
	"John",
	"Acts",
	"Romans",
	"1 Corinthians",
	"2 Corinthians",
	"Galatians",
	"Ephesians",
	"Philippians",
	"Colossians",
	"1 Thessalonians",
	"2 Thessalonians",
	"1 Timothy",
	"2 Timothy",
	"Titus",
	"Philemon",
	"Hebrews",
	"James",
	"1 Peter",
	"2 Peter",
	"1 John",
	"2 John",
	"3 John",
	"Jude",
	"Revelation",
}
M.oldtestament = {
	"Genesis",
	"Exodus",
	"Leviticus",
	"Numbers",
	"Deuteronomy",
	"Joshua",
	"Judges",
	"Ruth",
	"1 Samuel",
	"2 Samuel",
	"1 Kings",
	"2 Kings",
	"1 Chronicles",
	"2 Chronicles",
	"Ezra",
	"Nehemiah",
	"Esther",
	"Job",
	"Psalms",
	"Proverbs",
	"Ecclesiastes",
	"Solomon's Song",
	"Isaiah",
	"Jeremiah",
	"Lamentations",
	"Ezekiel",
	"Daniel",
	"Hosea",
	"Joel",
	"Amos",
	"Obadiah",
	"Jonah",
	"Micah",
	"Nahum",
	"Habakkuk",
	"Zephaniah",
	"Haggai",
	"Zechariah",
	"Malachi",
}
M.bofm = {
	"1 Nephi",
	"2 Nephi",
	"Jacob",
	"Enos",
	"Jarom",
	"Omni",
	"Words of Mormon",
	"Mosiah",
	"Alma",
	"Helaman",
	"3 Nephi",
	"4 Nephi",
	"Mormon",
	"Ether",
	"Moroni",
}

M.dnc = {
	"Doctrine and Covenants",
}
M.pgp = {
	"Moses",
	"Abraham",
	"Joseph Smith--Matthew",
	"Joseph Smith--History",
	"Articles of Faith",
}
M.short_books = {
	["Genesis"] = "gen",
	["Exodus"] = "ex",
	["Leviticus"] = "lev",
	["Numbers"] = "num",
	["Deuteronomy"] = "deut",
	["Joshua"] = "josh",
	["Judges"] = "judg",
	["Ruth"] = "ruth",
	["1 Samuel"] = "1-sam",
	["2 Samuel"] = "2-sam",
	["1 Kings"] = "1-kgs",
	["2 Kings"] = "2-kgs",
	["1 Chronicles"] = "1-chr",
	["2 Chronicles"] = "2-chr",
	["Ezra"] = "ezra",
	["Nehemiah"] = "neh",
	["Esther"] = "esth",
	["Job"] = "job",
	["Psalms"] = "ps",
	["Proverbs"] = "prov",
	["Ecclesiastes"] = "eccl",
	["Solomon's Song"] = "song",
	["Isaiah"] = "isa",
	["Jeremiah"] = "jer",
	["Lamentations"] = "lam",
	["Ezekiel"] = "ezek",
	["Daniel"] = "dan",
	["Hosea"] = "hosea",
	["Joel"] = "joel",
	["Amos"] = "amos",
	["Obadiah"] = "obad", -- only one chapter
	["Jonah"] = "jonah",
	["Micah"] = "micah",
	["Nahum"] = "nahum",
	["Habakkuk"] = "hab",
	["Zephaniah"] = "zeph",
	["Haggai"] = "hag",
	["Zechariah"] = "zech",
	["Malachi"] = "mal",
	["Matthew"] = "matt",
	["Mark"] = "mark",
	["Luke"] = "luke",
	["John"] = "john",
	["Acts"] = "acts",
	["Romans"] = "rom",
	["1 Corinthians"] = "1-cor",
	["2 Corinthians"] = "2-cor",
	["Galatians"] = "gal",
	["Ephesians"] = "eph",
	["Philippians"] = "philip",
	["Colossians"] = "col",
	["1 Thessalonians"] = "1-thes",
	["2 Thessalonians"] = "2-thes",
	["1 Timothy"] = "1-tim",
	["2 Timothy"] = "2-tim",
	["Titus"] = "titus",
	["Philemon"] = "philem", -- There's an exception with philemon. the URL must end in /1
	["Hebrews"] = "heb",
	["James"] = "james",
	["1 Peter"] = "1-pet",
	["2 Peter"] = "2-pet",
	["1 John"] = "1-jn",
	["2 John"] = "2-jn", -- also only one chapter.
	["3 John"] = "3-jn", -- also
	["Jude"] = "jude", -- also
	["Revelation"] = "rev",
	["1 Nephi"] = "1-ne",
	["2 Nephi"] = "2-ne",
	["Jacob"] = "jacob",
	["Enos"] = "enos",
	["Jarom"] = "jarom",
	["Omni"] = "omni",
	["Words of Mormon"] = "w-of-m",
	["Mosiah"] = "mosiah",
	["Alma"] = "alma",
	["Helaman"] = "hel",
	["3 Nephi"] = "3-ne",
	["4 Nephi"] = "3-ne",
	["Mormon"] = "morm",
	["Ether"] = "ether",
	["Moroni"] = "moro",
	["Doctrine and Covenants"] = "dc",
	["Official Declaration 1"] = "od",
	["Official Declaration 2"] = "od",
	["Moses"] = "moses",
	["Abraham"] = "abr",
	["Joseph Smith--Matthew"] = "js-m",
	["Joseph Smith--History"] = "js-h",
	["Articles of Faith"] = "a-of-f",
}
M.books = {
	"Genesis",
	"Exodus",
	"Leviticus",
	"Numbers",
	"Deuteronomy",
	"Joshua",
	"Judges",
	"Ruth",
	"1 Samuel",
	"2 Samuel",
	"1 Kings",
	"2 Kings",
	"1 Chronicles",
	"2 Chronicles",
	"Ezra",
	"Nehemiah",
	"Esther",
	"Job",
	"Psalms",
	"Proverbs",
	"Ecclesiastes",
	"Solomon's Song",
	"Isaiah",
	"Jeremiah",
	"Lamentations",
	"Ezekiel",
	"Daniel",
	"Hosea",
	"Joel",
	"Amos",
	"Obadiah",
	"Jonah",
	"Micah",
	"Nahum",
	"Habakkuk",
	"Zephaniah",
	"Haggai",
	"Zechariah",
	"Malachi",
	"Matthew",
	"Mark",
	"Luke",
	"John",
	"Acts",
	"Romans",
	"1 Corinthians",
	"2 Corinthians",
	"Galatians",
	"Ephesians",
	"Philippians",
	"Colossians",
	"1 Thessalonians",
	"2 Thessalonians",
	"1 Timothy",
	"2 Timothy",
	"Titus",
	"Philemon",
	"Hebrews",
	"James",
	"1 Peter",
	"2 Peter",
	"1 John",
	"2 John",
	"3 John",
	"Jude",
	"Revelation",
	"1 Nephi",
	"2 Nephi",
	"Jacob",
	"Enos",
	"Jarom",
	"Omni",
	"Words of Mormon",
	"Mosiah",
	"Alma",
	"Helaman",
	"3 Nephi",
	"4 Nephi",
	"Mormon",
	"Ether",
	"Moroni",
	"Doctrine and Covenants",
	"Moses",
	"Abraham",
	"Joseph Smith--Matthew",
	"Joseph Smith--History",
	"Articles of Faith",
}




return M